language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 4786156f81a9e109467876ae86e982383ed233526188814da06050f086b8fb45
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: FR+V6hfq4r3d4Pcm/kCCs8c/VpPIOjabqH+R2qa1BR5sLGhJxAhGKCGieGtMkTw2w0+65eT1Feyat/G4MgI/n3JivGg5J40HoFOb1LDLzltiUcxatzYlzyvo7dU4DuD5gY0k97HGOdroSlWchq2gA/Y3XfCNnM+u2kZnO1oXiKc33TOW2pEEQIAcD9+M9r0I3N/DDfgVOJ0VwcgFoslKDT/oKF2OKz1g6/gzIrtoZA4czLoWP5XY1c9puFzznOUyqUJ90n8aEo/U9QgwQJ0xSL33O5M+idbWVvkoE/leafo4NSvvSy9E1sB/t4YSnCU/a6HObfa1mB24/h7zMj2MfIJXZvBlB+A9ivWOTgq6Bfuc6P/u/uUQxYWcWr9YJuQowh57hF/ml5ASy7w59mljB7MqqwUzEu2mOla23/2al1B6gsgMinS6ek1+4Qv8+GCl0FXcAnatfzQUhgX0TknZZP2kKU5daVGWszs/Lov8+7HI4eCPrU87JQKZeUGGYT8gEld4KLmO7TmQVpVRP+sxx8qEm46Mdx5HAD4TDv2jmVLGvsyyoz+PVfeCa19WL646qdL0fOQj/s7DgkYF1sWuGK30NJi2QDmXrCKAaLu7s7WvgsRVKS439/Md1uoZCuUwBJOAYxlvPzcR3n2BCBnQsW7W8bmzrT9c2JKXmotHuGk=
  on:
    tags: true
    repo: yoctore/yocto-pm2-agent
before_install: npm install -g grunt-cli
install: npm install
